Repository fingerthief/recommendarr, pull requests merged in 2025-03, with the labels that each got.

#2 Dev/add sonarr radarr requesting
  .dockerignore
  .gitignore
  Dockerfile
  LICENSE
  README.md
  babel.config.js
  docker-compose.yml
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  reccommendarr/.gitignore
  reccommendarr/LICENSE
  reccommendarr/README.md
  reccommendarr/src/services/SonarrService.js
  src/App.vue
  src/assets/logo.png
  src/components/AISettings.vue
  src/components/HelloWorld.vue
  src/components/MovieRecommendations.vue
  src/components/Navigation.vue
  src/components/OpenAIConnection.vue
  src/components/RadarrConnection.vue
  src/components/Recommendations.vue
  src/components/SeriesList.vue
  src/components/SonarrConnection.vue
  src/components/TVRecommendations.vue
  src/main.js
  src/services/ImageService.js
  src/services/OpenAIService.js
  src/services/RadarrService.js
  src/services/SonarrService.js
  vue.config.js
Labels: enhancement

#3 Dev/improve layout and visual feedback
  package.json
  src/components/AISettings.vue
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: enhancement

#7 fix: dynamically set headers for Anthropic API
  src/components/AISettings.vue
  src/services/OpenAIService.js
Labels: bug

#8 Dev/add ability to change rec column count and model temp
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
Labels: enhancement

#11 Added a exepimental new "Recommendarr Score" based on AI analysis of it's trained data of various score sources.
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: enhancement

#13 Fixed bugged mobile layout
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
Labels: bug, enhancement

#16 Dev/improved recommendations filtering
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: enhancement

#17 Dev/llm prompt reworking
  README.md
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: bug, enhancement

#19 Comprehensive Recommendations System Overhaul
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: enhancement

#21 Adding Jellyfin Support, Jellyfin User Selection for Watch History, Chunked Prompting, UI Refinements
  src/App.vue
  src/components/AISettings.vue
  src/components/JellyfinConnection.vue
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/JellyfinService.js
  src/services/OpenAIService.js
Labels: enhancement

#24 Added dual layered filtering for recommendations to ensure unique items are shown.
  src/services/OpenAIService.js
Labels: bug, enhancement

#25 Enhanced Connection Management & Sonarr/Radarr Quality and Drive Location Options
  package.json
  src/App.vue
  src/components/AISettings.vue
  src/components/JellyfinConnection.vue
  src/components/MovieRecommendations.vue
  src/components/PlexConnection.vue
  src/components/RadarrConnection.vue
  src/components/SonarrConnection.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
  src/services/RadarrService.js
  src/services/SonarrService.js
Labels: enhancement

#26 Improved Recommendation Engine with Persistent Conversation Context
  package.json
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
Labels: enhancement

#27 History Page and Language Preference
  package.json
  src/App.vue
  src/components/History.vue
  src/components/MovieRecommendations.vue
  src/components/Navigation.vue
  src/components/TVRecommendations.vue
  src/services/OpenAIService.js
  src/services/RadarrService.js
  src/services/SonarrService.js
Labels: enhancement

#38 Add Tautulli integration and remove timeout limitations
  package-lock.json
  server/server.js
  server/services/ProxyService.js
  src/App.vue
  src/components/AISettings.vue
  src/components/MovieRecommendations.vue
  src/components/TVRecommendations.vue
  src/components/TautulliConnection.vue
  src/services/OpenAIService.js
  src/services/RadarrService.js
  src/services/SonarrService.js
  src/services/TautulliService.js
Labels: enhancement

#40 Adding docker-compose.remote.yml for pulliing and useing the remote images.
  README.md
  docker-compose.remote.yml
Labels: documentation

#62 Adding Trakt Integration and Fixed Watch History Bugs
  package-lock.json
  package.json
  public/index.html
  server/server.js
  src/App.vue
  src/components/AISettings.vue
  src/components/RequestRecommendations.vue
  src/components/TraktCallback.vue
  src/components/TraktConnection.vue
  src/services/ApiService.js
  src/services/JellyfinService.js
  src/services/OpenAIService.js
  src/services/PlexService.js
  src/services/TautulliService.js
  src/services/TraktService.js
Labels: bug, enhancement

#65 Fix/filtering recommendations and loading saved info
  package.json
  src/components/RequestRecommendations.vue
  src/services/OpenAIService.js
Labels: bug, enhancement
